source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NetRequest' do
pod 'Alamofire', '~> 4.4.0'
pod 'ObjectMapper', '~> 2.2.4'
pod 'SwiftyJSON' , '~> 3.1.4'
end

