//
//  ViewController.m
//  计算tableview的高度
//
//  Created by ld on 16/9/5.
//  Copyright © 2016年 ld. All rights reserved.
//

#import "ViewController.h"
#import "TableViewCell.h"
#import "UITableView+FDTemplateLayoutCell.h"

@interface ViewController ()

@property (nonatomic,copy) NSArray * datas;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
//    self.tableView.estimatedRowHeight = 88;
}


-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 5;
}

-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return [self.tableView fd_heightForCellWithIdentifier:@"mycell" cacheByIndexPath:indexPath configuration:^(TableViewCell * cell) {
        cell.myLable.text = self.datas[indexPath.row];
    }];
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    TableViewCell * cell = [tableView dequeueReusableCellWithIdentifier:@"mycell"];
    cell.myLable.text = self.datas[indexPath.row];
    return cell;
}

#pragma  mark - 懒加载
-(NSArray *)datas
{
    if (_datas == nil) {
        _datas = @[
                   @"adsffdsafasfdsafdsafdsafdsafdsafdfdsf",
                   @"adsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsf",
                   @"adsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfddsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsf",
                   @"adsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsasafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsf",
                   @"adsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsfadsffdsafasfdsafdsafdsafdsafdsafdfdsf",
                   ];
    }
    return _datas;
}
@end
